from pathlib import Path

main = Path("src/main.rs")
text = main.read_text()
changes = [
("const PLAYER_COLORS: [(f64, f64, f64); 4] = [\n    (0.25, 0.95, 0.35),\n    (0.95, 0.20, 0.22),\n    (0.20, 0.55, 1.0),\n    (1.0, 0.82, 0.18),\n];", "const PLAYER_COLORS: [(f64, f64, f64); 4] = [(0.98, 0.78, 0.08); 4];"),
("            PowerUpKind::Shrapnel => {\n                for _ in 0..5 {\n                    self.simulation.state.fire(owner, &self.simulation.config);\n                }\n                let mut angle = self\n                    .simulation\n                    .state\n                    .tanks\n                    .iter()\n                    .find(|t| t.player_id == owner)\n                    .map(|t| t.rotation_radians)\n                    .unwrap_or(0.0)\n                    - 0.65;\n                for projectile in self\n                    .simulation\n                    .state\n                    .projectiles\n                    .iter_mut()\n                    .rev()\n                    .filter(|p| p.owner == owner)\n                    .take(5)\n                {\n                    let speed = projectile.velocity.length();\n                    projectile.velocity = Vec2::new(angle.cos() * speed, angle.sin() * speed);\n                    projectile.remaining_lifetime = 2.0;\n                    angle += 0.26;\n                }\n            }", "            PowerUpKind::Shrapnel => {\n                for _ in 0..5 {\n                    self.simulation.state.fire(owner, &self.simulation.config);\n                }\n                let mut angle = self\n                    .simulation\n                    .state\n                    .tanks\n                    .iter()\n                    .find(|t| t.player_id == owner)\n                    .map(|t| t.rotation_radians)\n                    .unwrap_or(0.0)\n                    - 0.65;\n                for projectile in self\n                    .simulation\n                    .state\n                    .projectiles\n                    .iter_mut()\n                    .rev()\n                    .filter(|p| p.owner == owner)\n                    .take(5)\n                {\n                    let speed = projectile.velocity.length();\n                    projectile.velocity = Vec2::new(angle.cos() * speed, angle.sin() * speed);\n                    projectile.remaining_lifetime = 2.0;\n                    angle += 0.26;\n                }\n            }\n            PowerUpKind::Mine => {\n                if let Some(projectile) = self\n                    .simulation\n                    .state\n                    .projectiles\n                    .iter_mut()\n                    .rev()\n                    .find(|p| p.owner == owner)\n                {\n                    projectile.velocity = Vec2::ZERO;\n                    projectile.remaining_lifetime = 8.0;\n                }\n            }"),
("    for powerup in &runtime.powerups {\n        context.set_source_rgb(0.95, 0.72, 0.20);\n        context.arc(\n            powerup.position.x as f64,\n            powerup.position.y as f64,\n            11.0,\n            0.0,\n            std::f64::consts::TAU,\n        );\n        context.fill().ok();\n        context.set_source_rgb(0.08, 0.08, 0.08);\n        context.set_font_size(7.0);\n        context.move_to(\n            (powerup.position.x - 15.0) as f64,\n            (powerup.position.y + 3.0) as f64,\n        );\n        context.show_text(powerup.kind.label()).ok();\n    }", "    for powerup in &runtime.powerups {\n        draw_weapon_icon(context, powerup.position, powerup.kind);\n    }"),
("fn draw_game(context: &Context, width: i32, height: i32, runtime: &MatchRuntime) {", "fn draw_weapon_icon(context: &Context, position: Vec2, kind: PowerUpKind) {\n    let x = position.x as f64;\n    let y = position.y as f64;\n    context.save().ok();\n    context.set_source_rgb(0.08, 0.09, 0.10);\n    context.arc(x, y, 14.0, 0.0, std::f64::consts::TAU);\n    context.fill().ok();\n    context.set_source_rgb(0.98, 0.78, 0.08);\n    context.set_line_width(2.2);\n    match kind {\n        PowerUpKind::DoubleShot => {\n            context.move_to(x - 7.0, y - 4.0); context.line_to(x + 7.0, y - 4.0);\n            context.move_to(x - 7.0, y + 4.0); context.line_to(x + 7.0, y + 4.0);\n            context.stroke().ok();\n        }\n        PowerUpKind::MachineGun => {\n            for offset in [-6.0, 0.0, 6.0] { context.arc(x + offset, y, 2.5, 0.0, std::f64::consts::TAU); context.fill().ok(); }\n        }\n        PowerUpKind::Laser => {\n            context.move_to(x - 8.0, y + 7.0); context.line_to(x + 7.0, y - 7.0); context.stroke().ok();\n        }\n        PowerUpKind::GuidedMissile => {\n            context.move_to(x - 8.0, y); context.line_to(x + 8.0, y); context.stroke().ok();\n            context.move_to(x + 3.0, y - 5.0); context.line_to(x + 9.0, y); context.line_to(x + 3.0, y + 5.0); context.fill().ok();\n        }\n        PowerUpKind::Shrapnel => {\n            for angle in [0.0_f64, 1.2566, 2.5133, 3.7699, 5.0265] { context.move_to(x, y); context.line_to(x + angle.cos() * 8.0, y + angle.sin() * 8.0); }\n            context.stroke().ok();\n        }\n        PowerUpKind::Mine => {\n            context.arc(x, y, 6.0, 0.0, std::f64::consts::TAU); context.stroke().ok();\n            for angle in [0.0_f64, 1.5708, 3.1416, 4.7124] { context.move_to(x + angle.cos() * 6.0, y + angle.sin() * 6.0); context.line_to(x + angle.cos() * 10.0, y + angle.sin() * 10.0); }\n            context.stroke().ok();\n        }\n    }\n    context.set_source_rgb(0.08, 0.08, 0.08);\n    context.set_font_size(7.0);\n    context.move_to(x - 15.0, y + 24.0);\n    context.show_text(kind.label()).ok();\n    context.restore().ok();\n}\n\nfn draw_game(context: &Context, width: i32, height: i32, runtime: &MatchRuntime) {"),
("        let color = if runtime.ai_id == Some(tank.player_id) {\n            (0.38, 0.39, 0.41)\n        } else {\n            PLAYER_COLORS[tank.player_id.0 as usize % PLAYER_COLORS.len()]\n        };", "        let color = PLAYER_COLORS[tank.player_id.0 as usize % PLAYER_COLORS.len()];"),
("            // Laika gets subtle red sensor details.\n            context.set_source_rgb(0.70, 0.06, 0.07);", "            // Laika uses the same yellow-black palette with a bright sensor accent.\n            context.set_source_rgb(1.0, 0.86, 0.10);"),
("        context.set_source_rgb(1.0, 0.84, 0.22);", "        context.set_source_rgb(0.04, 0.04, 0.04);"),
]
for old, new in changes:
    if old not in text:
        raise SystemExit("required main.rs pattern missing")
    text = text.replace(old, new, 1)
main.write_text(text)

p = Path("src/game/powerup.rs")
t = p.read_text()
t = t.replace("pub const ALL: [Self; 5] = [", "pub const ALL: [Self; 6] = [", 1)
t = t.replace("        Self::Shrapnel,\n    ];", "        Self::Shrapnel,\n        Self::Mine,\n    ];", 1)
t = t.replace("    Shrapnel,\n}", "    Shrapnel,\n    Mine,\n}", 1)
t = t.replace('            Self::Shrapnel => "✣ FRAG",', '            Self::Shrapnel => "✣ FRAG",\n            Self::Mine => "✦ MINE",', 1)
p.write_text(t)
